version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_AGENCY=1
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Jhon
      - CLI_LASTNAME=Doe
      - CLI_BIRTHDATE=1999-03-01
      - CLI_ID=104121
      - CLI_NUMBER=1
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_AGENCY=2
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Jhon
      - CLI_LASTNAME=Doe
      - CLI_BIRTHDATE=1999-03-02
      - CLI_ID=104122
      - CLI_NUMBER=2
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_AGENCY=3
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Jhon
      - CLI_LASTNAME=Doe
      - CLI_BIRTHDATE=1999-03-03
      - CLI_ID=104123
      - CLI_NUMBER=3
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_AGENCY=4
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Jhon
      - CLI_LASTNAME=Doe
      - CLI_BIRTHDATE=1999-03-04
      - CLI_ID=104124
      - CLI_NUMBER=4
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_AGENCY=5
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=Jhon
      - CLI_LASTNAME=Doe
      - CLI_BIRTHDATE=1999-03-05
      - CLI_ID=104125
      - CLI_NUMBER=5
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
